### ISSUE TITLE
Hopes to remove the scroll bar provided by the browser.

### ISSUE THREAD

**Issue by Howardzhangdqs** [chriskuech/vs-code-viewer-extension#42]
![image](https://user-images.githubusercontent.com/75195784/208279905-aa2cd67a-3dce-4faf-9e7c-466cb653dcd8.png)

It can be remove with just:
```css
/* For google or Edge */
::-webkit-scrollbar {
    display: none;
}

body {
    margin: 0;
}
```
![image](https://user-images.githubusercontent.com/75195784/208280033-954aa879-c89b-49eb-a044-6ee0262b41ea.png)

And will look better……in some ways:smile:
